contact_links:
  - name: Usage question & discussion
    url: https://github.com/Marcono1234/unsafe-address-sanitizer/discussions
    about: Ask usage questions and discuss this Unsafe Sanitizer in GitHub Discussions.
