# Based on https://github.com/gradle/actions/blob/v4.0.0/docs/dependency-submission.md#general-usage

name: Gradle Dependency Submission

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    steps:
    - name: Check out sources
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@v4
